Vagrant.configure(2) do |config|
  config.vm.box = "fedora/23-cloud-base"
  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.provider "virtualbox" do |vbx|
  vbx.customize ["modifyvm", :id, "--memory", "4096"]
  vbx.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end
  config.vm.synced_folder "devstack/", "/opt/stack/devstack"
  config.vm.provision :shell, path: "bootstrap.sh"
end
